### ISSUE TITLE
Error: invalid magic word 'headcount'

### ISSUE THREAD

**Issue by Alexia** [elifoster/HeaderCount#2]
This occurs when enabling the extension.

```
[1c111988] /FTB_Wiki MWException from line 337 of /includes/MagicWord.php: Error: invalid magic word 'headcount'

Backtrace:

#0 /includes/MagicWord.php(262): MagicWord->load(string)
#1 /includes/parser/Parser.php(5212): MagicWord::get(string)
#2 /extensions/HeaderCount/HeaderCount.hooks.php(5): Parser->setFunctionHook(string, string)
#3 [internal function]: HeaderCountHooks::setupParser(Parser)
#4 /includes/Hooks.php(201): call_user_func_array(string, array)
#5 /includes/parser/Parser.php(328): Hooks::run(string, array)
#6 [internal function]: Parser->firstCallInit()
#7 /includes/StubObject.php(105): call_user_func_array(array, array)
#8 /includes/StubObject.php(129): StubObject->_call(string, array)
#9 /includes/cache/MessageCache.php(1035): StubObject->__call(string, array)
#10 /includes/cache/MessageCache.php(1035): StubObject->firstCallInit()
#11 /includes/cache/MessageCache.php(1012): MessageCache->getParser()
#12 /includes/Message.php(1130): MessageCache->transform(string, boolean, Language, Title)
#13 /includes/Message.php(797): Message->transformText(string)
#14 /includes/Message.php(860): Message->toString()
#15 /includes/OutputPage.php(958): Message->text()
#16 /includes/OutputPage.php(1006): OutputPage->setHTMLTitle(Message)
#17 /includes/page/Article.php(514): OutputPage->setPageTitle(string)
#18 /includes/actions/ViewAction.php(44): Article->view()
#19 /includes/MediaWiki.php(490): ViewAction->show()
#20 /includes/MediaWiki.php(287): MediaWiki->performAction(Article, Title)
#21 /includes/MediaWiki.php(714): MediaWiki->performRequest()
#22 /includes/MediaWiki.php(508): MediaWiki->main()
#23 /index.php(41): MediaWiki->run()
#24 {main}
```

**Comment by elifoster** [comment]
Are you using the extension.json to enable it, or require_once?

**Comment by Alexia** [comment]
The extension.json file.
